openapi: 3.2.0
info:
  title: Calendar Misc API
  version: v1
  summary: Calendar API for Moroccan Holidays and Open Business Days
  description: '## Try Calendar API


    This interactive panel allows you to explore the whole API and to understand the different datastructures and parameters

    used by every endpoint.'
  contact:
    name: UNRAVEL DESIGNS
    url: https://unraveldesigns.ma
    email: ud@unraveldesigns.ma
  license:
    name: Proprietary
servers:
- url: /
  description: Casablanca
security:
- apiKey: []
- sessionCookie: []
tags:
- name: Misc
  description: Misc endpoints
  x-tag-expanded: false
paths:
  /health:
    get:
      tags:
      - Misc
      summary: API Health
      operationId: HealthHealth
      responses:
        '200':
          description: Request fulfilled, document follows
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemHealth'
      deprecated: false
components:
  schemas:
    SystemHealth:
      properties:
        api_status:
          type: boolean
        appname:
          type: string
          default: calendar-api
      type: object
      required: []
      title: SystemHealth
  securitySchemes:
    apiKey:
      type: apiKey
      description: API Key authentication and authorization.
      name: X-API-KEY
      in: header
    sessionCookie:
      type: apiKey
      description: Session cookie authentication.
      name: session
      in: cookie
externalDocs:
  url: https://docs.calendar-api.ma
  description: Documentation externe de l'API
